services:

    web:
        image: nginx:latest
        volumes:
            - ./client:/usr/share/nginx/html
        ports:
            - "80:80"
    db:
        image: mysql:latest # use latest version of mysql
        container_name: db # add a name for the container
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        volumes:
            - ./db:/var/lib/mysql
        expose:
            - '3306:3306'
        depends_on:
            - "web"

    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
            - 8082:80
        depends_on:
            - "db"

    node:
        image: "node:latest"
        container_name: "node"
        user: "node"
        restart: unless-stopped
        working_dir: /home/node/app
        environment:
        - NODE_ENV=production
        volumes:
        - ./server:/home/node/app
        - ./client:/var/www/html 
        ports:
        - "3000:3000"
        expose:
        - "3000"
        depends_on:
        - "db"
        command: sh -c "npm install && npm start"