services:

    web:
        image: nginx:latest
        container_name: "web_SDEP"
        volumes:
            - ./client:/usr/share/nginx/html
        ports:
            - "80:80"
            
    db:
        image: mariadb:latest
        container_name: "db_SDEP"
        restart: always
        environment:
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        volumes:
            - ./db:/var/lib/mysql
        expose:
            - '3306:3306'
        depends_on:
            - "web"

    adminer:
        image: adminer
        container_name: "adminer_SDEP"
        restart: always
        ports:
        - 8080:8080
        depends_on:
            - "db"

    node:
        image: "node:latest"
        container_name: "node_SDEP"
        user: "node"
        restart: unless-stopped
        working_dir: /home/node/app
        environment:
        - NODE_ENV=production
        volumes:
        - ./server:/home/node/app
        - ./client:/var/www/html 
        ports:
        - "3000:3000"
        expose:
        - "3000"
        depends_on:
        - "adminer"
        command: sh -c "npm install && npm start"